import fs from 'fs'
import { compileFromFile } from 'json-schema-to-typescript'

console.log('Converting JSON Schemas to Typescript type definitions...\n')

const comment = `
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript during the build
 * process (.vite/prebuild-types.mjs). DO NOT MODIFY IT BY HAND. Instead, modify the
 * source JSONSchema file, and run json-schema-to-typescript to regenerate this file.
 */
`

compileFromFile('./public/config/schemas/NodePackage.schema.json', {
  additionalProperties: false,
  style: {
    singleQuote: true,
    semi: false,
  },
  bannerComment: comment,
}).then((ts) => fs.writeFileSync('./src/renderer/types/NodePackage.d.ts', ts))

compileFromFile('./public/config/schemas/NodeProgram.schema.json', {
  additionalProperties: false,
  style: {
    singleQuote: true,
    semi: false,
  },
  bannerComment: comment,
}).then((ts) => fs.writeFileSync('./src/renderer/types/NodeProgram.d.ts', ts))
