/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NodeCollectionSchema = NodeCollection

export interface NodeCollection {
  name: string
  nodes: Node[]
}
export interface Node {
  id: string
  title: string
  fields: Field[]
}
export interface Field {
  id: string
  type: string
  arguments: Arguments
}
export interface Arguments {
  label?: string
  inputLabel?: string
  outputLabel?: string
  inputDatatype?: string
  outputDatatype?: string
  inputMulti?: boolean
  values?: string[]
  default?: string
}
