/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript during the build
 * process (.vite/prebuild.mjs). DO NOT MODIFY IT BY HAND. Instead, modify the source
 * JSONSchema file, and run json-schema-to-typescript to regenerate this file.
 */

export type NodeCollectionSchema = NodeCollection
export type Field = {
  id: string
  type: 'InputOutput' | 'Select' | 'List'
  props?: {}
} & Field1
export type Field1 = InputOutputField | SelectField | ListField
export type InputOutputFieldProps = (
  | {
      [k: string]: unknown
    }
  | {
      [k: string]: unknown
    }
) & {
  inputLabel?: string
  outputLabel?: string
  inputDatatype?: string
  outputDatatype?: string
  inputMulti?: boolean
}

export interface NodeCollection {
  name: string
  nodes: Node[]
}
export interface Node {
  id: string
  title: string
  fields: Field[]
}
export interface InputOutputField {
  type?: 'InputOutput'
  props: InputOutputFieldProps
}
export interface SelectField {
  type?: 'Select'
  props: SelectFieldProps
}
export interface SelectFieldProps {
  label?: string
  values: string[]
  default: string
}
export interface ListField {
  type?: 'List'
  props?: ListFieldProps
}
export interface ListFieldProps {
  label?: string
}
